"""High-level client for ICOMON kitchen scales."""

from __future__ import annotations

from types import TracebackType

from .adapter import Adapter, create_adapter
from .ble.backend import BleBackend, DefaultBleBackend
from .config import COMM_PROTOCOL, Config
from .device import KitchenScaleDevice
from .exceptions import DeviceNotFoundError
from .models import ScannedDevice


class KitchenScaleClient:
    """Discover and connect to ICOMON / Fitdays+ kitchen scales over BLE."""

    def __init__(
        self,
        config: Config | None = None,
        *,
        backend: BleBackend | None = None,
    ) -> None:
        self.config = config or Config()
        self._backend = backend or DefaultBleBackend()
        self._adapter: Adapter = create_adapter(self.config, backend=self._backend)

    @property
    def adapter(self) -> Adapter:
        """Low-level BLE adapter used for direct bleak access."""
        return self._adapter

    @property
    def protocol(self) -> str:
        """Selected communication protocol (``ble``)."""
        return COMM_PROTOCOL

    async def scan_for_device(
        self,
        *,
        name: str | None = None,
        address: str | None = None,
        timeout: float | None = None,
    ) -> KitchenScaleDevice:
        """Scan for a scale by advertised name or explicit address."""
        if address:
            device_name = name or self.config.ble_name
            return KitchenScaleDevice(
                address,
                name=device_name,
                config=self._with_address(address, device_name),
                transport=self._adapter.create_transport(address),
            )

        discovered = await self.scan(name=name, timeout=timeout)
        if not discovered:
            msg = f"no BLE device found with name {name or self.config.ble_name!r}"
            raise DeviceNotFoundError(msg)
        best = discovered[0]
        return KitchenScaleDevice(
            best.address,
            name=best.name,
            config=self._with_address(best.address, best.name),
            transport=self._adapter.create_transport(best.address),
        )

    async def scan(
        self,
        *,
        name: str | None = None,
        timeout: float | None = None,
    ) -> list[ScannedDevice]:
        """Return matching scales discovered during a BLE scan."""
        target_name = name or self.config.ble_name
        scan_timeout = timeout if timeout is not None else self.config.scan_timeout
        discovered = await self._backend.discover(scan_timeout)
        matches: list[ScannedDevice] = []
        for device, advertisement in discovered.values():
            device_name = advertisement.local_name or device.name or ""
            if device_name != target_name:
                continue
            matches.append(
                ScannedDevice(
                    name=device_name,
                    address=device.address,
                    rssi=advertisement.rssi,
                )
            )
        return sorted(
            matches,
            key=lambda item: item.rssi if item.rssi is not None else -999,
            reverse=True,
        )

    def _with_address(self, address: str, name: str) -> Config:
        return Config(
            address=address,
            ble_name=name,
            model=self.config.model,
            device_type=self.config.device_type,
            mtu=self.config.mtu,
            scan_timeout=self.config.scan_timeout,
            app_reply_body=self.config.app_reply_body,
        )

    async def connect(self) -> None:
        """Open a connection using ``Config.address``."""
        await self._adapter.connect()

    async def disconnect(self) -> None:
        """Close the adapter connection."""
        await self._adapter.disconnect()

    async def __aenter__(self) -> KitchenScaleClient:
        await self.connect()
        return self

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None:
        await self.disconnect()


# Backwards-compatible alias generated by the template.
Client = KitchenScaleClient
