"""High-level client for ICOMON kitchen scales."""

from __future__ import annotations

import logging

from .ble.backend import BleBackend, DefaultBleBackend
from .ble.transport import BleTransport
from .config import Config
from .device import Device
from .exceptions import DeviceNotFoundError
from .models import ScannedDevice

_LOGGER = logging.getLogger(__name__)


class KitchenScaleClient:
    """Discover and connect to ICOMON / Fitdays+ kitchen scales over BLE."""

    def __init__(
        self,
        config: Config | None = None,
        *,
        backend: BleBackend | None = None,
    ) -> None:
        self.config = config or Config()
        self._backend = backend or DefaultBleBackend()

    async def scan_for_device(
        self,
        *,
        name: str | None = None,
        address: str | None = None,
        timeout: float | None = None,
    ) -> Device:
        """Scan for a scale by advertised name or explicit address."""
        if address:
            device_name = name or self.config.ble_name
            return Device(
                address,
                name=device_name,
                config=self._with_address(address, device_name),
                transport=BleTransport(address, backend=self._backend),
            )

        discovered = await self.scan(name=name, timeout=timeout)
        if not discovered:
            msg = f"no BLE device found with name {name or self.config.ble_name!r}"
            raise DeviceNotFoundError(msg)
        best = discovered[0]
        _LOGGER.info(
            "using %s at %s rssi=%s",
            best.name,
            best.address,
            best.rssi,
        )
        return Device(
            best.address,
            name=best.name,
            config=self._with_address(best.address, best.name),
            transport=BleTransport(best.address, backend=self._backend),
        )

    async def scan(
        self,
        *,
        name: str | None = None,
        timeout: float | None = None,
    ) -> list[ScannedDevice]:
        """Return matching scales discovered during a BLE scan."""
        target_name = name or self.config.ble_name
        scan_timeout = timeout if timeout is not None else self.config.scan_timeout
        _LOGGER.info("scanning for %r (timeout=%.1fs)", target_name, scan_timeout)
        discovered = await self._backend.discover(scan_timeout)
        matches: list[ScannedDevice] = []
        for device, advertisement in discovered.values():
            device_name = advertisement.local_name or device.name or ""
            if device_name != target_name:
                continue
            matches.append(
                ScannedDevice(
                    name=device_name,
                    address=device.address,
                    rssi=advertisement.rssi,
                )
            )
        _LOGGER.info("scan matched %d device(s) named %r", len(matches), target_name)
        return sorted(
            matches,
            key=lambda item: item.rssi if item.rssi is not None else -999,
            reverse=True,
        )

    def _with_address(self, address: str, name: str) -> Config:
        return Config(
            address=address,
            ble_name=name,
            model=self.config.model,
            device_type=self.config.device_type,
            mtu=self.config.mtu,
            scan_timeout=self.config.scan_timeout,
            app_reply_body=self.config.app_reply_body,
            fun_info_timeout=self.config.fun_info_timeout,
        )


# Backwards-compatible alias generated by the template.
Client = KitchenScaleClient
